locals_without_parens = [
  checkbox: 2,
  checkbox: 3,
  color_input: 2,
  color_input: 3,
  date_input: 2,
  date_input: 3,
  date_select: 2,
  date_select: 3,
  datetime_local_input: 2,
  datetime_local_input: 3,
  datetime_select: 2,
  datetime_select: 3,
  email_input: 2,
  email_input: 3,
  file_input: 2,
  file_input: 3,
  form_for: 3,
  form_for: 4,
  error_tag: 2,
  hidden_input: 2,
  hidden_input: 3,
  live_component: 2,
  input: 2,
  input: 3,
  label: 1,
  label: 2,
  label: 3,
  label: 4,
  multiple_select: 3,
  multiple_select: 4,
  number_input: 2,
  number_input: 3,
  password_input: 2,
  password_input: 3,
  radio_button: 3,
  radio_button: 4,
  range_input: 2,
  range_input: 3,
  reset: 1,
  reset: 2,
  search_input: 2,
  search_input: 3,
  select: 2,
  select: 3,
  select: 4,
  submit: 1,
  submit: 2,
  telephone_input: 2,
  telephone_input: 3,
  text_input: 2,
  text_input: 3,
  textarea: 2,
  textarea: 3,
  time_input: 2,
  time_input: 3,
  time_select: 2,
  time_select: 3,
  url_input: 2,
  url_input: 3
]

[
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  locals_without_parens: locals_without_parens,
  export: [locals_without_parens: locals_without_parens]
]
